"""Run the planner agent directly and print a human-readable plan."""

from __future__ import annotations

import argparse
import datetime
import sys

from dotenv import load_dotenv


def print_plan(plan: dict) -> None:
    posts = plan.get("posts", [])
    print()
    print(f"PLANNER RESULT - {plan.get('month', 'unknown month')}")
    print("=" * 72)
    source = plan.get("generation_source", "unknown")
    source_label = {
        "llm": "LLM response",
        "rss_fallback": "RSS fallback",
    }.get(source, source)
    print(f"Generated by: {source_label}")
    print(f"Total posts: {len(posts)}")

    for number, post in enumerate(posts, 1):
        special_day = post.get("special_day")
        label = f"Post {number} - {special_day}" if special_day else f"Post {number}"
        print()
        print(label)
        print("-" * len(label))
        print(f"Date       : {post.get('scheduled_date') or 'Not provided'}")
        print(f"Time       : {post.get('scheduled_time') or 'Not provided'}")
        print(f"Format     : {post.get('format') or 'Not provided'}")
        print(f"Theme      : {post.get('theme') or 'Not provided'}")
        print(f"RSS source : {post.get('trend_source') or 'Not provided'}")
        print(f"Article    : {post.get('trend_article_title') or 'Not provided'}")
        print(f"Article URL: {post.get('trend_article_url') or 'Not provided'}")
        print(f"Brief      : {post.get('brief') or 'Not provided'}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Test the Wimbee planner agent without email, database, or posting."
    )
    parser.add_argument("month", help="Month to plan, in YYYY-MM format (example: 2026-10)")
    args = parser.parse_args()

    try:
        datetime.datetime.strptime(args.month, "%Y-%m")
    except ValueError:
        parser.error("month must use YYYY-MM format, for example 2026-10")

    load_dotenv()

    from agents.planner_agent import run_planner

    try:
        plan = run_planner(args.month)
    except Exception as exc:
        print(f"Planner failed: {exc}", file=sys.stderr)
        return 1

    print_plan(plan)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
